"""empty message

Revision ID: 8ccb37d8d9dc
Revises: 9cea1220a83e
Create Date: 2019-11-10 12:59:46.902938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccb37d8d9dc'
down_revision = '9cea1220a83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("INSERT INTO todolists(name) VALUES('uncategorized')")
    op.execute('UPDATE todos SET todo_list_id=1 WHERE todo_list_id IS NULL')

    op.alter_column('todos', 'todo_list_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    op.create_foreign_key(None, 'todos', 'todolists', ['todo_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_list_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
