"""empty message

Revision ID: 9cea1220a83e
Revises: b67e1b15ad90
Create Date: 2019-11-10 12:31:01.228969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cea1220a83e'
down_revision = 'b67e1b15ad90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('todos', sa.Column(
        'todo_list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['todo_list_id'], ['id'])

    op.execute('INSERT INTO todolists(name) VALUE(uncategorized)')
    op.execute('UPDATE todos SET todo_list_id=1 WHERE todo_list_id IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todo_list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
